

def count3(dna, base):
    match=[c==base for c in dna]
    return sum(match)

print(count3("ctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacgu","c"))

from timeit import timeit
dir(timeit)

print(timeit.timeit(stmt=count3("ctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacguctguctguacgu","c"), number=1))

